//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOffice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectOffice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ADD_BTN_PICTURE {
            get {
                object obj = ResourceManager.GetObject("ADD_BTN_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проектный офис.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BASKET_BTN_PICTURE {
            get {
                object obj = ResourceManager.GetObject("BASKET_BTN_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- MySQL dump 10.13  Distrib 8.0.34, for Win64 (x86_64)
        ///--
        ///-- Host: 127.0.0.1    Database: project_office
        ///-- ------------------------------------------------------
        ///-- Server version	8.0.30
        ///
        ////*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        ////*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        ////*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        ////*!50503 SET NAMES utf8 */;
        ////*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
        ////*!40103 SET TIME_ZONE=&apos;+00:00&apos; */;
        ////* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data_dump {
            get {
                return ResourceManager.GetString("data_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDIT_BTN_PICTURE {
            get {
                object obj = ResourceManager.GetObject("EDIT_BTN_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GEAR_WHEEL_PICTURE {
            get {
                object obj = ResourceManager.GetObject("GEAR_WHEEL_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HIDE_PICTURE {
            get {
                object obj = ResourceManager.GetObject("HIDE_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #UserID;log;pass;h
        ///9;1_nW9nRO;048Q~8F);3657c8b2441df7a617d74ca6db6921ebd7502c08dd489bdb6b0b5ca06ade150de563c0f941dced7fabf3b44518a77a22162971ea6ac39f6a4ef6fdfd915f443c
        ///
        ///10;8q@NJX5R;aB%3kH?Z;56a83f23adbcb123a490ea61de1fc30292f21d2a22fa6b521b03cce0c3158079f2a71b3cfb480710c70b5716b73a4b693ff70011b36af5866a1442b1bfa047d7
        ///
        ///11;l$C3Z3da;EFbmV$O*;44fd5df9c491fb201f933ff5c510f37c3d43ec0dc24bf5f8f10581223d84b645b7dc980841204c965b007afc49ca93172962f55cc7a6bf66c60949e30ebe1326
        ///
        ///12;ueB~J5mk;KSC$)@Vj;41da80ad8c95b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PLUG_PICTURE {
            get {
                object obj = ResourceManager.GetObject("PLUG_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PROJECT_OFFICE_ICON {
            get {
                object obj = ResourceManager.GetObject("PROJECT_OFFICE_ICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROJECT_OFFICE_LOGO {
            get {
                object obj = ResourceManager.GetObject("PROJECT_OFFICE_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PROJECT_OFFICE_LOGO_SVG {
            get {
                object obj = ResourceManager.GetObject("PROJECT_OFFICE_LOGO_SVG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SHOW_PICTURE {
            get {
                object obj = ResourceManager.GetObject("SHOW_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap USR_PLUG_PICTURE {
            get {
                object obj = ResourceManager.GetObject("USR_PLUG_PICTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
